### ISSUE TITLE
this.updateState is not a function when setting state

### ISSUE THREAD

**Issue by dchisey** [joeLepper/whom#1]
Error in button-change.js in dynamic mode. I'm getting this when I manually type a name into any one of the buttons. Reading through the logs, I tried an ID from the person json files as well but to no avail.

I'm also getting this when I try to add a new button - `this.updateState` seems to be where the issue lies.

![image](https://user-images.githubusercontent.com/25090145/35770313-43abcce6-08de-11e8-83e1-960974f60004.png)

**Comment by joeLepper** [comment]
This was, fortunately, resolved by the massive rewrite that I had hanging around locally.
