### ISSUE TITLE
With HMR gone, should we add auto-refresh?

### ISSUE THREAD

**Issue by dchisey** [joeLepper/whom#33]
In digging around about HMR, I found this: [electron-reload](https://www.npmjs.com/package/electron-reload). Would this be a good alternative to HMR? Seems very similar to nodemon or webpack hard reloads.

**Comment by joeLepper** [comment]
Yeah. I'd far prefer to have the page issue a refresh than the hot reloading which is getting between us and react – as it more closely resembles how the app will behave for an actual user.

**Comment by joeLepper** [comment]
Do it as an extra commit on https://github.com/joeLepper/whom/pull/32

**Comment by joeLepper** [comment]
Done somewhere. I forget which commit. Closing.
